export const optionScores = {
    "I don't feel particularly guilty": 0,
    "I feel guilty over many things I have done or should have done": 1,
    "I feel quite guilty most of the time.": 2,
    "I feel guilty all of the time.": 3,
    "I feel the same about myself as ever": 0,
    "I have lost confidence in myself.": 1,
    "I am disappointed in myself.": 2,
    "I dislike myself.": 3,
    "I do not feel pressurized.": 0,
    "I feel pressurized much of the time.": 1,
    "I am pressurized all the time.": 2,
    "I am so sad or unhappy that I can't stand it.": 3,
    "I am not discouraged about my future": 0,
    "I feel more discouraged about my future than I used to.": 1,
    "I do not expect things to work out for me.": 2,
    "I feel my future is hopeless and will only get worse.": 3,
    "I do not feel like a failure.": 0,
    "I have failed more than I should have.": 1,
    "As I look back, I see a lot of failures.": 2,
    "I feel I am a total failure as a person.": 3,
    "I make decisions about as well as ever.": 0,
    "I find it more difficult to make decisions than usual.": 1,
    "I have much greater difficulty in making decisions than I used to.": 2,
    "I have trouble making any decisions.": 3,
    "I don't have any thoughts of killing myself.": 0,
    "I have thoughts of killing myself, but I would not carry them out.": 1,
    "I would like to kill myself.": 2,
    "I would kill myself if I had the chance.": 3,
    "I have not experienced any change in my sleeping": 0,
    "I sleep somewhat more than usual": 1,
    "I sleep somewhat less than usual": 2,
    "I sleep a lot more than usual": 3,
    "I sleep a lot less than usual": 3,
    "I sleep most of the day": 4,
    "I wake up 1-2 hours early and can't get back to sleep": 3,
    "I can concentrate as well as ever": 0,
    "I can't concentrate as well as usual": 1,
    "It's hard to keep my mind on anything for very long": 2,
    "I find I can't concentrate on anything": 3,
    "I have not experienced any change in my appetite": 0,
    "My appetite is somewhat less than usual": 1,
    "My appetite is somewhat greater than usual": 1,
    "My appetite is much less than before": 2,
    "My appetite is much greater than usual": 2,
    "I have no appetite at all": 3,
    "I crave food all the time": 3,
    "I do not feel restless": 0,
    "I'm often fidgety, wringing my hands, or need to shift how I am sitting": 1,
    "I have impulses to move about and am quite restless": 2,
    "At times, I am unable to stay seated and need to pace around": 3,
    "I see myself as equally worthwhile and deserving as other people": 0,
    "I am more self-blaming than usual": 1,
    "I largely believe that I cause problems for others": 2,
    "I think almost constantly about major and minor defects in my life": 3,
    "I do not wake up at night": 0,
    "I have a restless, light sleep with a few brief awakenings each night": 1,
    "I wake up at least once a night, but I go back to sleep easily": 2,
    "I awaken more than once a night and stay awake for 20 minutes or more, more than half the time": 3,
    "There is no change in my usual level of energy": 0,
    "I get tired more easily than usual": 1,
    "I have to make a big effort to start or finish my usual daily activities (for example, shopping, homework, cooking, or going to work)": 2,
    "I really cannot carry out most of my usual daily activities because I just don't have the energy": 3,
    "There is no change from usual in how interested I am in other people or activities": 0,
    "I notice that I am less interested in people or activities": 1,
    "I find I have interest in only one or two of my formerly pursued activities": 2,
    "I have virtually no interest in formerly pursued activities": 3
};